### ISSUE TITLE
not connected

### ISSUE THREAD

**Issue by bertdeelman** [Dirnei/node-red-contrib-zigbee2mqtt-devices#1]
Hi,

I don't get it working. I added the ikea remote card and fill in the broker values. After a deploy there is a message: not connected. 

- there is a typo: broker instead of brocker
- bridge config node. Base MQTT Topic should be password.  

Is there any documentation how to use this nice addon. 

Regards,
Bert

**Comment by Dirnei** [comment]
sorry currently not. i will start documentation shortly. i didn't expect that someone will use it that quickly ^^

i guess i forgot to add the protocol in front of the hostname, e.g.: mqtt://localhost

**Comment by Dirnei** [comment]
typos are fixed. let me now if you get the connection working. Here is a screenshot of the documentation i just wrote for this, which is available in the next update.
![image](https://user-images.githubusercontent.com/912432/94426997-b181f500-018e-11eb-9fdf-54196f179686.png)

**Comment by bertdeelman** [comment]
Hi,

Thanks for the fast update. ;)

I can't select a device at the ikea remote card. 

Two errors at the debug messages:
- ReferenceError: options is not defined
- TypeError: Cannot read property 'isConnected' of null

Regards,
Bert

**Comment by Dirnei** [comment]
Please try to update to version 0.7.3. Sound like a bug that i fixed today

**Comment by Dirnei** [comment]
@bertdeelman any updates? i hope you got it working. if not let me know ;)

**Comment by bertdeelman** [comment]
Hi,

I switched to deconz/Conbee II. It has an integration with Homey. zigbee2mqtt is a very nice product, but there is no integration (yet?) with Homey. Homey is not very famous for there Zigbee implementation. That is why is need to migrate that part to another solution. 

Regards,
Bert
