### ISSUE TITLE
Refresh device-list and manual entry

### ISSUE THREAD

**Issue by Boia11** [Dirnei/node-red-contrib-zigbee2mqtt-devices#105]
Hi!
When I try to refresh device-list nothing happered but I need to use manual entry because "Failed to request device-list!" but sometimes the node forbidden user-friendly name and stop working after deploy.

I use Home Assistant OS 6.1 on RPi 4 with Node-RED Add-on 9.2.1 and latest version of this plugin (0.19.2)

https://user-images.githubusercontent.com/10048197/126401846-667c448f-7724-4670-892d-b88681154a52.mp4

**Comment by Dirnei** [comment]
It should work after your first deployment, if this is the correct name that is used in the mqtt messages. Unfortunately i havn't had a chance to look at the problem that it does not fetch in Home Assistant. I only know that HA host the http endpoint on a different base URL but without testing gear I was not able to resolve the issue. 

You could host node-red standalone and than you should be able to fetch the device names.

**Comment by Boia11** [comment]
No no, it works the first time when deployed, but if you make a mistake and open the node (without modifying it like the video), the node forgets the device that I entered manually and when you deploy nodes stop working

**Comment by Andreas-Huber** [comment]
Fix for querying the device list is implemented in #119 and should be shipped with the 0.19.5 release in the next few days.

For the broken fallback, I opened a new issue: #119
