### ISSUE TITLE
occasional error on ikea remote device, missing null

### ISSUE THREAD

**Issue by itupsk** [Dirnei/node-red-contrib-zigbee2mqtt-devices#114]
Problem from #110 still continues.
Log message says:
```
[error] TypeError: Cannot read property 'replace' of null
at MqttSubscription.callback (/data/node_modules/node-red-contrib-zigbee2mqtt-devices/dist/nodes/devices-ikea.js:90:51)
```
so, in your last fix missing `null` in condition:

`
if (message.action === undefined || message.action === "") {
`

https://github.com/Dirnei/node-red-contrib-zigbee2mqtt-devices/blob/0.19.3/src/nodes/devices-ikea.js#L85

**Comment by Dirnei** [comment]
Published a new release right now! Should be available for update in node-red soon! Thanks again for your help :)
