### ISSUE TITLE
0.69 to 2.16 - cant upgrade

### ISSUE THREAD

**Issue by scargill** [Dirnei/node-red-contrib-zigbee2mqtt-devices#124]
Hi

Im using Node-RED (up to date) on RPI4.  A while ago I tried updating your nodes from 0.69 to 2.16 and many of my Zigbee items stopped... today I upgraded Zigbee2MQTT to the latest version first in the hope this would fix things -- no.

Any thoughts on the matter? Simply upgrading NR-Contrib-zigbee2mqtt and not touching anything else, several of my Zigbee devices including Aquara triple switches and others, simply fail (red triangle in node and a message saying that nodes stopped).

Thanks to rpi-clone I've been able to back up but I can't get past this...

I can upgrade other unrelated NR nodes no problem.

Any help would be truly appreciated.

Regards

Pete

**Comment by Dirnei** [comment]
Are you sure that you are on the right repo? The current version is 0.19.5 ;)

**Comment by Andreas-Huber** [comment]
No feedback. Closing this since it is clearly another library with a similar name. But not ours.
