### ISSUE TITLE
Custom icons not set for all configs

### ISSUE THREAD

**Issue by Andreas-Huber** [Dirnei/node-red-contrib-zigbee2mqtt-devices#20]
Regarding the icons is see two minor issues.
- We could improve the selected icons and not use the label everywhere.
- Sometimes there is a space missing after the icon.

Proposed fix: go through all HTML files and check the space. Change icons if better ones are available.

![2020-10-15 13_50_07-Node-RED](https://user-images.githubusercontent.com/13376471/96119787-c5975780-0eed-11eb-935d-bf702e1d9853.png)

**Comment by Dirnei** [comment]
When you do that could you please also have a look for missing description. i know that there are some nodes, but not where :)

**Comment by Andreas-Huber** [comment]
Put the missing descriptions I found and could not fix immediately into the new issue #29 .
