### ISSUE TITLE
Investigate why devicelist is sometimes empty

### ISSUE THREAD

**Issue by Dirnei** [Dirnei/node-red-contrib-zigbee2mqtt-devices#32]
Quickfix: Send empty payload to "zigbee2mqtt/bridge/config/devices/get" to get a fresh device list

> Sometimes a full-deploy helps also

**Comment by Dirnei** [comment]
I haven't seen it in a while. I guess I fixed it :)

**Comment by Dirnei** [comment]
Just got a message in discord about that. MAYBE, jut MAYBE it isn't fixed.....

**Comment by Dirnei** [comment]
You can configre a "base path" in the node-red settings. if it is configured it is not possible to request the device list

```
// By default, the Node-RED UI is available at http://localhost:1880/
// The following property can be used to specify a different root path.
// If set to false, this is disabled.
//httpAdminRoot: '/admin',
// httpAdminRoot: '/nodered',
```

**Comment by Dirnei** [comment]
My last comment was fixed with #47. I can't see any problems anymore and @Andreas-Huber also reported no problems while testing it with his new devices I will close it once and for all :)

**Comment by Andreas-Huber** [comment]
Did not notice it until now.

**Comment by Andreas-Huber** [comment]
Happened to me again with version 0.16.0 and 0.16.1 on my production system.

Steps to Reproduce the Bug:
1. Stop Node-Red (in my case docker-compose down)
2. Create a new flow (not entirely sure if that is necessary)
3. Add generic lamp node (I have new not configured devices in my network)
4. Edit the node and select a bridge.
5. Click on the add new Zigbee device edit button
6. Click on the devices dropdown. **Device list is empty**
7. Somehow a device is selected anyway.

7. Deploy
8. Open device config again. The dropdown is filled.

**Screencast**
https://drive.google.com/file/d/1r4H_LgeblRvBTsk5FZnGZz3AtlbQKYX5/view?usp=sharing

**Comment by QBANIN** [comment]
I'm having this issue with last HA + Z2M Edge.

**Comment by Dirnei** [comment]
@QBANIN I guess with HA you mean HomeAssistant? If so, there is currently no support for that. You have to open the nodered directly to get it working.

**Comment by QBANIN** [comment]
> @QBANIN I guess with HA you mean HomeAssistant? If so, there is currently no support for that. You have to open the nodered directly to get it working.

Ouch.. that's too bad :(

**Comment by Dirnei** [comment]
It's not really that bad ;) You only have to open a new tab a open the node-red, basically change the port in the url to 1880. When we have time to install HA and this plugin we will have a look how we can integrate it but for now you have to do this small workaround. sorry :(

**Comment by jchmielniak** [comment]
I'm having the same problem (nodered 1.2.6, z2m 1.6.2) The other Node "node-red-contrib-zigbee2mqtt" shows the device list properly.

**Comment by Dirnei** [comment]
Did you mean z2m version 1.16.2? 1.6.2 seems a bit old. Did the Quickfix from the first message worked for you?

**Comment by jchmielniak** [comment]
Sure it was a typo 1.16.2. Quickfix doesn't work.
I log following mqtt messages on node-red start:
2020-12-11T14:11:41+0100 zigbee2mqtt/bridge/config/groups 1607692301699
2020-12-11T14:11:41+0100 zigbee2mqtt/bridge/config/devices/get 1607692301700
2020-12-11T14:11:41+0100 zigbee2mqtt/bridge/log {"message":[{"ID":10,"devices":[],"friendly_name":"empty","optimistic":true}, ... ,"type":"groups"}
2020-12-11T14:11:41+0100 zigbee2mqtt/bridge/config/devices [{"dateCode":"20201113","friendly_name":"Coordinator","ieeeAddr":"0x00124b0021600033","lastSeen":1607692301703, ...

**Comment by jchmielniak** [comment]
It is a bug in z2m 1.16.2. Fixed in dev branch. 
API is going to chang. Could you please implement a new API as well.
https://github.com/Koenkk/zigbee2mqtt/issues/5289

**Comment by Dirnei** [comment]
Thanks for the hint! I will have a look
