### ISSUE TITLE
Sunrise / Daylight node?

### ISSUE THREAD

**Issue by Andreas-Huber** [Dirnei/node-red-contrib-zigbee2mqtt-devices#41]
Would it make sense to add a node for sunrise/sundown or in general to get insight if the sun is shining or not?
It's strictly speaking not really part of this lib. And there might be libs that do that better.
I have not researched this yet, just wanted to note the thought.

**Comment by Dirnei** [comment]
Good suggestion. We should look if there is a good node for that and if not, integrate it. I'm also thinking about changing the name of the node to something more smarthomie if you know what I mean. But that's something to think about when we close to 1.0

**Comment by Dirnei** [comment]
I moved this issue to the discussion. See #68
