### ISSUE TITLE
Devices not listed when node-red is using httpAdminRoot setting

### ISSUE THREAD

**Issue by brunoamaral** [Dirnei/node-red-contrib-zigbee2mqtt-devices#46]
I was looking at the code and it looks like this line is keeping the devices from being listed. 

https://github.com/Dirnei/node-red-contrib-zigbee2mqtt-devices/blob/c619bd74c4e89b89f84da8b8c659cbcc531b3469/src/zigbee2mqtt-config.html#L96

I am going to test changing it to a relative path and report back.

` $.getJSON('./z2m/devices/' + bridgeId + '/router/all/all', function (data) { `

**Comment by Dirnei** [comment]
That would be great if this works

**Comment by brunoamaral** [comment]
It didn't work as expected, but something like this does work:

```js
$.getJSON((window.location) .protocol + "//" + (window.location).host + "/" + (window.location).pathname.split('/')[1] + '/z2m/devices/' + bridgeId + '/router/all/all', function (data) {
```

If you're ok with the fix, I can open a pull request sometime next week.

**Comment by Dirnei** [comment]
Yeah looks good. Thanks a lot!
