### ISSUE TITLE
bride-log node

### ISSUE THREAD

**Issue by Andreas-Huber** [Dirnei/node-red-contrib-zigbee2mqtt-devices#6]
# bridge-log node

The Bridge-log node provides functionality to filter the [Zigbee2MQTT](https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgelog) log.

## Requirements 
The user should get a UI to filter the log types.
- If a log is selected, a node output is dynamically created.
- By default, the node provides one output per log type.
- There should be a switch to direct all messages to one output instead of one per message type.

**Comment by Dirnei** [comment]
## Example payloads
```{"message":"announce","meta":{"friendly_name":"0x14b457fffe4572a9"},"type":"device_announced"}```
```{"message":"left_network","meta":{"friendly_name":"0x14b457fffe4572a9"},"type":"device_removed"}```
```{"message":"interview_started","meta":{"friendly_name":"0x14b457fffe4572a9"},"type":"pairing"}```
```{"message":{"friendly_name":"0x14b457fffe4572a9"},"type":"device_connected"}```
```{"message":"interview_failed","meta":{"friendly_name":"0x14b457fffe4572a9"},"type":"pairing"}```
```{"message":{"from":"0x14b457fffe4572a9","to":"Fernbedienung 2"},"type":"device_renamed"}```

**Comment by Andreas-Huber** [comment]
@Dirnei what do you think about the style for the checkboxes in the config.

![image](https://user-images.githubusercontent.com/13376471/96137758-5295dd00-0efd-11eb-8ea0-914d50765335.png)

I prefer the last three. I also tried that with icons but that looks to cluttered.

**Comment by Dirnei** [comment]
The last ones are preffered. In addition i would lower the size of your descriptioin
