### ISSUE TITLE
Climate sensor should output which sensor it's from AND separate outputs for temp / humidity would be a nice option

### ISSUE THREAD

**Issue by rekcodocker** [Dirnei/node-red-contrib-zigbee2mqtt-devices#75]
Normally you can derive from msg.topic which device  it's from. 
Because Climate Sensor keeps this a secret I have to add the sensor-name in a topic for each sensor, before I forward it to a graph.
Please add the name of the climate sensor to msg.topic so I can forward the message directly to a graph.

Also, in addition, it would be nice if it had the option of multiple outputs so I can connect the Humidity output to a humidity-graph, temp to temp, etcetera.

**Comment by Dirnei** [comment]
Should be no problem at all. But to be consistent with the outputs of all other nodes I would only output the device name
