### ISSUE TITLE
Problems after release 0.18.0 

### ISSUE THREAD

**Issue by ceysa75** [Dirnei/node-red-contrib-zigbee2mqtt-devices#80]
Hi,

after updating to 0.18.0 I experienced some problems, which howewer are addressed in the changelog (fix one bridge-config and all the errors will get away). So, that worked. However, in the Manage pallette still an error is shown.
![image](https://user-images.githubusercontent.com/37417641/105170303-0ae6a900-5b1d-11eb-9c06-95503c22bee1.png)

Then I thought, better to remove the whole contrib and install it again. However, the contrib cannot be removed. Obviously, 2 config nodes are in use which as a matter of fact is not true. I deleted both config nodes. Any help would be appreciated. My prefered way would be to remove the whole package and then reinstall it.

Best Regards

Ceysa

**Comment by Andreas-Huber** [comment]
I already saw and fixed that yesterday. The changes are in the master branch but have not been released yet. I might release a new version.
Reinstalling would not fix the issue in the palette, since it is an issue in the packages.json. We simply forgot to remove the file from there. Everything else should work.


I'll leave this issue open until the update is out and confirmed to work.

**Comment by ceysa75** [comment]
Dear Andreas,

good to hear that. Thanks for the fast response. Another issue I just have noticed is that under context data / global some entries appear which have not been there before (in these entries somehow all my zigbee devices appear). Is this resulting from the recent update ?
![image](https://user-images.githubusercontent.com/37417641/105176407-85b3c200-5b25-11eb-8271-9a8d5903ecdc.png)
 
Regards

**Comment by Dirnei** [comment]
@ceysa75 No these entries are expected and are there since day one. That entries are application data from this package that are needed to run.

**Comment by Andreas-Huber** [comment]
Hi Ceysa, we released a new version (0.18.0), that includes a fix for that. You will still see the error after the update.

![2021-01-20 17_44_13-Window](https://user-images.githubusercontent.com/13376471/105207454-d805da80-5b47-11eb-8b9d-fd251f505e8b.png)

But after the mandatory node-red restart it is gone.

![image](https://user-images.githubusercontent.com/13376471/105207431-d1776300-5b47-11eb-9428-c754162428d3.png)

That was just an issue in the page.json. So there is nothing wrong with your installation. So a reinstall won't be neccessary.

BTW: If you are a new user, this release also includes a [getting started guide](https://github.com/Dirnei/node-red-contrib-zigbee2mqtt-devices/blob/master/docs/getting-started.md), step by step.

Regards Andreas

**Comment by ceysa75** [comment]
Thank you so much for your efforts....

Regards
Ceysa
